# @!host:dragonfury
# @!os:linux
# @!install:644:$HOME/.config/wireplumber/wireplumber.conf.d/local.conf

monitor.alsa.rules = [
	{
		matches = [{ device.name = "alsa_card.pci-0000_2f_00.4" }]
		actions = {
			update-props = {
				device.nick = "System"
				device.description = "System"
				device.intended-roles = ["Default", "Music", "Movie", "Game", "Production"]
			}
		}
	}
	{
		matches = [
			{ node.name = "alsa_output.pci-0000_2f_00.4.analog-stereo" }
			{ node.name = "alsa_input.pci-0000_2f_00.4.analog-stereo" }
		]
		actions = {
			update-props = {
				node.nick = "Headphones"
				node.description = "Headphones"
			}
		}
	}
	{
		matches = [{ device.name = "alsa_card.pci-0000_2d_00.1" }]
		actions = {
			update-props = {
				# device.nick = "Graphics Card"
				# device.description = "Graphics Card"
				# device.intended-roles = ["Notification"]
				device.disabled = true
			}
		}
	}
	#{
	#	matches = [{ node.name = "alsa_output.pci-0000_2d_00.1.hdmi-stereo-extra1" }]
	#	actions = {
	#		update-props = {
	#			node.nick = "DisplayPort"
	#			node.description = "DisplayPort"
	#		}
	#	}
	#}
	{
		matches = [{ device.name = "alsa_card.usb-GN_Audio_A_S_Jabra_Engage_75_03334881200F-00" }]
		actions = {
			update-props = {
				device.nick = "Jabra"
				device.description = "Jabra"
				device.intended-roles = ["Communication"]
			}
		}
	}
	{
		matches = [
			{ node.name = "alsa_output.usb-GN_Audio_A_S_Jabra_Engage_75_03334881200F-00.iec958-stereo" }
			{ node.name = "alsa_input.usb-GN_Audio_A_S_Jabra_Engage_75_03334881200F-00.mono-fallback" }
		]
		actions = {
			update-props = {
				node.nick = "Headset"
				node.description = "Headset"
			}
		}
	}
	{
		matches = [
			{ media.role = "", media.class = "Stream/Input/Audio" }
			{ media.role = "", media.class = "Stream/Output/Audio" }
		]
		actions = {
			update-props = {
				media.role = "Default"
			}
		}
	}
]

monitor.bluez.rules = [
	{
		matches = [{device.name = "bluez_card.34_09_C9_73_E5_24"}]
		actions = {
			update-props = {
				bluez5.hw-volume = []
			}
		}
	}
]
