# @!os:linux
# @!user:dracowizard
# @!dirmode:700:$HOME/.gnupg
# @!install:644:$HOME/.gnupg/gpg-agent.conf

allow-preset-passphrase
enable-ssh-support
default-cache-ttl 28800
default-cache-ttl-ssh 28800
max-cache-ttl 57600
max-cache-ttl-ssh 57600
pinentry-program /usr/bin/pinentry-qt
